services:
  mysql:
    image: mysql:8.0
    container_name: museum_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./rest_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - museum_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rest_api:
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    container_name: rest_api
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT:-3306}/${MYSQL_DATABASE}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - HOST=${API_HOST:-0.0.0.0}
      - PORT=${API_PORT:-8000}
      - DEBUG=${DEBUG:-false}
    ports:
      - "8080:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - museum_network
    volumes:
      - ./rest_api:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vk_bot:
    build:
      context: ./vk_bot
      dockerfile: Dockerfile
    container_name: vk_bot
    restart: unless-stopped
    environment:
      - HOST=${VK_BOT_HOST:-0.0.0.0}
      - PORT=${VK_BOT_PORT:-9001}
      - DEBUG=${VK_DEBUG:-false}
      - VK_BOT_TOKEN=${VK_BOT_TOKEN}
      - WEBHOOK_PATH=${WEBHOOK_PATH:-/vk-bot/callback}
    ports:
      - "9001:9001"
    networks:
      - museum_network
    volumes:
      - ./vk_bot:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  museum_network:
    driver: bridge